# Generated by Django 2.2.15 on 2020-08-25 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.DateField(auto_now_add=True, verbose_name='Registration data')),
                ('modification', models.DateField(auto_now=True, verbose_name='Modification data')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('name', models.CharField(max_length=60, verbose_name='Name')),
                ('short_description', models.TextField(max_length=60, verbose_name='Short description')),
                ('long_description', models.TextField(verbose_name='Long description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/%Y/%m/', verbose_name='Image')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('price', models.FloatField(verbose_name='Price')),
                ('promotional_price', models.FloatField(default=0, verbose_name='Promotional price')),
                ('product_type', models.CharField(choices=[('V', 'Variation'), ('S', 'Simple')], default='V', max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
