# Generated by Django 2.2.15 on 2020-08-25 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20200825_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, help_text="Don't need to type", null=True, unique=True, verbose_name='Slug'),
        ),
    ]
