# Generated by Django 2.2.15 on 2020-09-04 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20200826_2103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='name',
            new_name='variation',
        ),
        migrations.AlterUniqueTogether(
            name='variation',
            unique_together={('product', 'variation')},
        ),
    ]
