# Generated by Django 2.2.15 on 2020-09-04 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20200903_2252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='variation',
            new_name='name',
        ),
        migrations.AlterUniqueTogether(
            name='variation',
            unique_together={('product', 'name')},
        ),
    ]
