# Generated by Django 2.2.15 on 2020-08-25 23:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Costumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.DateField(auto_now_add=True, verbose_name='Registration data')),
                ('modification', models.DateField(auto_now=True, verbose_name='Modification data')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('age', models.PositiveIntegerField(max_length=3, verbose_name='Age')),
                ('birth_date', models.DateField(verbose_name='Birth date')),
                ('cpf', models.CharField(max_length=11)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CostumerAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50, verbose_name='Street')),
                ('number', models.CharField(max_length=5, verbose_name='number')),
                ('adjunct_address', models.CharField(max_length=30, verbose_name='Adjunct address')),
                ('district', models.CharField(max_length=30, verbose_name='District')),
                ('zip_code', models.CharField(max_length=8, verbose_name='Zip code')),
                ('city', models.CharField(max_length=30, verbose_name='City')),
                ('state', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina')], default='SP', max_length=2, verbose_name='state')),
                ('costumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costumer.Costumer')),
            ],
        ),
    ]
