# Generated by Django 2.2.15 on 2020-08-25 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costumer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumer',
            name='age',
            field=models.PositiveIntegerField(verbose_name='Age'),
        ),
    ]
