# Generated by Django 2.2.15 on 2020-09-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costumer', '0004_auto_20200903_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumer',
            name='age',
            field=models.PositiveIntegerField(verbose_name='Age'),
        ),
    ]
