# Generated by Django 2.2.15 on 2020-09-03 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costumer', '0005_auto_20200903_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumeraddress',
            name='costumer',
            field=models.ForeignKey(auto_created=True, on_delete=django.db.models.deletion.CASCADE, to='costumer.Costumer'),
        ),
    ]
