# Generated by Django 2.2.15 on 2020-08-25 21:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.DateField(auto_now_add=True, verbose_name='Registration data')),
                ('modification', models.DateField(auto_now=True, verbose_name='Modification data')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('total', models.FloatField()),
                ('status', models.CharField(choices=[('A', 'Approved'), ('R', 'Registered'), ('C', 'Canceled'), ('I', 'In approval'), ('T', 'In transport'), ('D', 'Delivered')], default='R', max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=60)),
                ('product_id', models.PositiveIntegerField()),
                ('variation', models.CharField(max_length=50)),
                ('variation_id', models.PositiveIntegerField()),
                ('price', models.FloatField()),
                ('promotional_price', models.FloatField(default=0)),
                ('image', models.CharField(max_length=2000)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
            ],
            options={
                'verbose_name': 'Order item',
                'verbose_name_plural': 'Order items',
            },
        ),
    ]
