# Generated by Django 2.2.15 on 2020-09-03 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='total quantity'),
            preserve_default=False,
        ),
    ]
